name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      
env:
   DOTNET_VERSION: '3.1.404'
   DOTNET_PLATFORM_VERSION: '5.0.0'

jobs:
  build_client_job:
    runs-on: ubuntu-latest
    name: Build Client Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Make node modules directory
        run: mkdir -p ./Client/node_modules

      - name: Run npm install
        run: npm install --prefix ./Client ./Client

      - name: Run Gulp tasks
        run: gulp --gulpfile '${{ github.workspace }}/Client/gulpfile.js' css:prod
   
  build-dotnet_job:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build
        run: |
          dotnet build --configuration Release
   
          
  deploy_dotnet_job:
    runs-on: ubuntu-latest
    name: Build and Deploy dotnet Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Deploy dotnet
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
        with:
          dotnet-version: ${{ env.DOTNET_PLATFORM_VERSION }} 
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_DUNE_0EBA5C303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Client" # App source code path
          api_location: "Api" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_DUNE_0EBA5C303 }}
          action: "close"
